linters:
  disable-all: true
  enable:
    - deadcode
    - depguard
    - errcheck
    - gochecknoinits
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nolintlint
    - prealloc
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace

linters-settings:
  lll:
    line-length: 120
  gci:
    local-prefixes: github.com/makkes/gitlab-cli

issues:
  exclude-rules:
    # ignore errcheck for code under a /test folder
    - path: "test/*"
      linters:
        - errcheck
    # ignore errcheck for flags.Parse (it is expected that we flag.ExitOnError)
    # ignore response.WriteError as it always returns the err it was passed
    - source: "flags.Parse|response.WriteError"
      linters:
        - errcheck
