repos:
- repo: local
  hooks:
  - id: go-mod-tidy
    name: go mod tidy
    entry: make mod-tidy
    files: "(.*\\.go|go.mod|go.sum)$"
    language: system
    stages: [commit]
    pass_filenames: false
  - id: golangci-lint
    name: golangci-lint
    entry: make lint
    language: system
    files: "(.*\\.go|go.mod|go.sum)$"
    pass_filenames: false
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
    stages: [commit]
    exclude: "^(cmd\/get\/projects\/projects_test|table\/table_test)\\.go$"
  - id: check-yaml
    args: ["-m", "--unsafe"]
    stages: [commit]
  - id: mixed-line-ending
    args: ["-f", "lf"]
    exclude: \.bat$
    stages: [commit]
  - id: no-commit-to-branch
    stages: [commit]
  - id: check-added-large-files
    stages: [commit]
  - id: check-case-conflict
    stages: [commit]
  - id: check-merge-conflict
    stages: [commit]
  - id: check-executables-have-shebangs
    stages: [commit]
    exclude: skopeo/static/.+$
  - id: check-symlinks
    stages: [commit]
  - id: end-of-file-fixer
    stages: [commit]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.17.0
  hooks:
  - id: gitlint
    stages: [commit-msg]
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.5
  hooks:
  - id: shfmt
    stages: [commit]
    args: ["-s", "-i", "2"]
  - id: script-must-have-extension
    stages: [commit]
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.8.0.3
  hooks:
  - id: shellcheck
    stages: [commit]
    args: ["-e", "SC2211"]
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.30.0
  hooks:
  - id: markdownlint
    stages: [commit]
