name: Test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: asdf-vm/actions/install@v1
    - name: Lint code
      run: make lint
    - name: pre-commit
      uses: pre-commit/action@v2.0.3
      with:
        extra_args: --all-files
      env:
        SKIP: no-commit-to-branch,golangci-lint
    - name: Run unit tests
      run: make test
