name: Test
on: [pull_request]
jobs:
  echo:
    name: Echo
    runs-on: ubuntu-latest
    steps:
    - name: Echo some env
      env:
        MY_VAR: ${{ github.event.pull_request.id }}
      run: echo $MY_VAR
